version: '3.4'

services:
  bot:
    image: ${DOCKER_REGISTRY-}bot
    container_name: bot
    build:
      context: .
      dockerfile: Bot/Dockerfile
    environment:
      - UseDocker=true
      - CONNECTION_STRING=Server=db,1433;Database=WeatherBot;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=true
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    restart: always
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/bot-db:/var/lib/sql/data
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341