name: Trigger auto deployment for bot-app-20240917162311

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/bot-app-20240917162311-AutoDeployTrigger-0f8f6700-b61e-4c81-b6f3-c08bf2a0eada.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BOTAPP20240917162311_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BOTAPP20240917162311_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BOTAPP20240917162311_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: bot20240917135912.azurecr.io
          registryUsername: ${{ secrets.BOTAPP20240917162311_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BOTAPP20240917162311_REGISTRY_PASSWORD }}
          containerAppName: bot-app-20240917162311
          resourceGroup: WeatherApp
          imageToBuild: bot20240917135912.azurecr.io/bot-app-20240917162311:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


